version: '3.3'

services:
  mysql:
    image: mysql
    volumes:
      - didentity-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: aosai6aH
      MYSQL_USER: didentity
      MYSQL_PASSWORD: aosai6aH 
      MYSQL_DATABASE: digital_identity

  backend:
    image: openjdk
    working_dir: /app
    #    ports: 
    #      - 8080:8080 # Disable for production!! 
    volumes:
      - ./src/digitalIdentity-backend:/app
    command: bash -c "./mvnw spring-boot:run"
    environment:
      MYSQL_HOST: mysql
      HOSTNAME: 
      # Mail Relay Configuration:
      MAIL_RELAY_HOST: smtp.gmail.com
      MAIL_RELAY_PORT: 587
      MAIL_RELAY_USERNAME: FILL ME
      MAIL_RELAY_PASSWORD: FILL ME
      MAIL_RELAY_SMTP: "true"
      MAIL_RELAY_STARRTTLS: "true"
      # Lissi API Configuration
      LISSI_API_URL: 
      LISSI_API_AUTH_CLIENT_ID: FILL ME
      LISSI_API_AUTH_CLIENT_SECRET : FILL ME


  frontend:
    image: node
    ports:
      - 80:4200
    working_dir: /app
    volumes:
      - ./src/digitalIdentity-frontend:/app
    command: bash -c "npm install -g @angular/cli && npm install && ng serve --host 0.0.0.0 --port 4200 --disable-host-check --proxy-config src/proxy.conf.docker.json"

volumes:
  didentity-mysql-data:
