version: '3.3'

services:
  mysql:
    image: mysql
    volumes:
      - didentity-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: aosai6aH
      MYSQL_USER: didentity
      MYSQL_PASSWORD: aosai6aH 
      MYSQL_DATABASE: digital_identity

  backend:
    image: openjdk
    working_dir: /app
    ports: 
      - 8080:8080 # Disable for production!!
    volumes:
      - ./src/digitalIdentity-backend:/app
    command: bash -c "./mvnw spring-boot:run"
    environment:
      HOSTNAME: localhost
      MYSQL_HOST: mysql

  frontend:
    image: node
    ports:
      - 80:4200
    working_dir: /app
    volumes:
      - ./src/digitalIdentity-frontend:/app
    command: bash -c "npm install -g @angular/cli && npm install && ng serve --host 0.0.0.0 --port 4200 --proxy-config src/proxy.conf.docker.json"

volumes:
  didentity-mysql-data: