version: "3.3"

services:
  frontend-build:
    image: node
    working_dir: /app
    volumes:
      - ./src/digitalIdentity-frontend:/app
    command: bash -c "npm install -g @angular/cli && npm install && npm run build"