openapi: 3.0.3
info:
  version: 0.3.2
  title: "Digital Identity - Backend API"
  description: "This API describes how the DIdentity Server behaves. It manages the user data, their processing as well as their storage. It also offers other functions, such as the validation of digital identities."
  # TODO
  #termsOfService: hallo
  #contact:
  #  name: tbd
  #  url: tbd
  #  email: blank@test.de
  #license: 
  #  name: license-name
  #  url: tbd
  
servers:
  - url: http://localhost:8080
    description: Backend Server
  #- url: http://localhost:4242
  #  description: Frontend Service
    
  
paths: 
  /auth/register:
    post:
      description: Create a new user entry in the database.
      parameters: 
        - name: name
          in: "query"
          schema: 
            type: string
          description: The name of the new user.
          example: John
          
        - name: surname
          in: "query"
          schema:
            type: string
          description: The surrname of the new user.
          example: Doe 
          
        - name: birthday
          in: "query"
          schema:
            type: string
            format: date
          description: The birthday of the new user.
          example: 01.01.1980
          
        - name: email
          in: "query"
          schema:
            type: string
          description: The email adress of the new user. This will be used later on for login.
          example: john.doe@example.org

        - name: company
          in: "query"
          schema:
            type: string
          description: The company the user works at. 
          example: "Friedrich-Alexander Universitaet Erlangen-Nuernberg"
          
        - name: user_role
          in: "query"
          schema:
            type: string
            enum: [employee, guest, "HR employee", admin]
          description: This is the role of the user in the system.
          example: "employee"
          
        - name: team
          in: "query"
          required: false
          schema:
            type: string
          description: The team the user belongs to.
          example: "Lehrstul 42"
          
        
          

      # TODO for a later sprint: add login-session 
      # see comments below /database/query for more info
      
      responses:
        201:
          description: Successful creation of the user.
        400:
          description:  Bad Request.
        401:
          description: Unauthorized. Token not found or not valid.
      
          
          
  /auth/login:
    post:
      description: Check whether there is a valid username + password combination to get a JWT (JSON Web Token).
      parameters: 
        - name: e_mail
          in: "query"
          schema: 
            type: string
          description: The e-mail adress of the user.
          example: john.doe@example.org

        - name: password
          in: "query"
          schema:
            type: string
          description: The e-mail adress of the new user. This will be used later on for login.
          example: Wm7&+TpZcw9>U3qV
      
      responses: # This will need to return a JWT in a later version / sprint and + returns the id of the current user
        200:
          description: Successful login.
        400:
          description:  Bad Request.
        401:
          description: Unauthorized. Token not found or not valid.
          
          
  /user/{id}:
    get: 
      description: Get userdata of person
       
      
    post: 
      description: Get userdata of person
      
  
  /user/{id}/qr:
    get: 
      description: Get the (lissy)-QR image 

  /user/all:
    get: 
      description: Get a list of all users
      # all data
      
          
          
  /database/query:
    get:
      description: Pull data from the database
      deprecated: true
      responses:
        200:
          description: Successful pull from database.
        400:
          description:  Bad Request.
        401:
          description: Unauthorized. Token not found or not valid.
          
  # This will need use a JWT in a later version / sprint in order to manage whether someone is logged in  This can expire. Therefore there needs to be a response which tells the client to update the JWT. This can be done via a /auth/refreshtolen POST request
          
      